include:
  - ./packages/back-nest/docker-compose.yml

services:
  backend:
    build:
      context: ./packages/back-nest
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./packages/back-nest:/app
      - /app/node_modules
      - ./repos:/app/repos
      - ./.repos:/app/.repos:ro
    environment:
      - DATABASE_PRIVATE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NODE_ENV=development
    depends_on:
      - db
    command: sh -c "yarn install && ./scripts/clone-repos.sh && yarn prebuild && yarn build && yarn start:dev"

  frontend:
    image: node:20
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./packages/webapp-next:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:1337
    depends_on:
      - backend
    command: sh -c "yarn install && yarn dev"
